---
language: "ruby"

rvm:
  - "1.9.3"

env:
  global:
    - BEAKER_project="CI for puppet module reidmv/pe_mco_shell_agent"
    - BEAKER_department="tse"
    - BEAKER_destroy="yes"
    - BEAKER_set="ec2"
    - BEAKER_CREATED_BY="reid"
    - BEAKER_BUILD_URL="https://travis-ci.org/${TRAVIS_REPO_SLUG}/builds/${TRAVIS_BUILD_ID}"
    # Secret keys should be configured in the Travis-CI project settings:
    # - AWS_ACCESS_KEY_ID=<secret>
    # - AWS_SECRET_ACCESS_KEY=<secret>

before_install:
  - './spec/acceptance/bin/ci-setup.sh'

script:
  - '[ "${TRAVIS_SECURE_ENV_VARS}" = "true" ] && ./spec/acceptance/bin/ci-run.sh bundle exec rspec spec/acceptance'

deploy:
  provider: puppetforge
  user: reidmv
  password:
    secure: "VUg41sqtgJRJp84x8WiNtpa7gkAiOJdiiORZODt2Z0UITuriOAl30o7HV5lNe+wIDnaKIVE98Jk2evFHjViuGeknJz5rrB3FGK7OOCrIUVxnUFT8ITuRecU9T4tWO2lfHJKq47y5kAeFBFXxw4mGyALt/pJZwZ3CZ0jUHFQq4h0="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
