HOSTS:
  centos-66-x64:
    roles:
      - agent
    platform: el-6-x86_64
    box: puppetlabs/centos-6.6-64-nocm
    hypervisor: vagrant
CONFIG:
  type: pe
  pe_dir: https://s3.amazonaws.com/pe-builds/released/3.7.2
  pe_ver: 3.7.2
  masterless: true
