HOSTS:
  centos-66-x64-master:
    roles:
      - master
      - dashboard
      - database
    platform: el-6-x86_64
    box: puppetlabs/centos-6.6-64-nocm
    hypervisor: vagrant
  centos-66-x64-agent:
    roles:
      - agent
    platform: el-6-x86_64
    box: puppetlabs/centos-6.6-64-nocm
    hypervisor: vagrant
CONFIG:
  type: pe
  pe_dir: https://s3.amazonaws.com/pe-builds/released/3.7.2
  pe_ver: 3.7.2
  disable_iptables: true
  vagrant_memsize: 4096
